services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  cacher:
    build:
      context: .
      dockerfile: ./cmd/cacher/Dockerfile
    depends_on:
      - redis
      - mongodb
      - fetcher
    restart: always
    ports:
      - "8081:8081"
    environment:
      - HEALTH_PORT=8081
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  fetcher:
    build:
      context: .
      dockerfile: ./cmd/fetcher/Dockerfile
    depends_on:
      - redis
    restart: always
    ports:
      - "8080:8080"
    environment:
      - HEALTH_PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  signal_gen:
    build:
      context: .
      dockerfile: ./cmd/signal_gen/Dockerfile
    depends_on:
      - redis
      - cacher
    restart: always
    ports:
      - "8082:8082"
    environment:
      - HEALTH_PORT=8082
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8082/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s


volumes:
  redis_data:
  mongo_data: