services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  cacher:
    build:
      context: .
      dockerfile: ./cmd/cacher/Dockerfile
    depends_on:
      - redis
      - mongodb
      - fetcher
    restart: always
  fetcher:
    build:
      context: .
      dockerfile: ./cmd/fetcher/Dockerfile
    depends_on:
      - redis
    restart: always
  signal_gen:
    build:
      context: .
      dockerfile: ./cmd/signal_gen/Dockerfile
    depends_on:
      - redis
      - cacher
    restart: always


volumes:
  redis_data:
  mongo_data: