{
 "title": "fetcher_v2",
 "description": "Received & Published trade counts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "trade rate (1/seconds)",
   "type": "timeseries",
   "description": "rate of received trade info from binance\nrate of published trade info to redis",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(trades_received_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(trades_published_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trade info age (milliseconds)",
   "type": "timeseries",
   "description": "quantiles of the:\nsystem date - trade date\n(note: system date errors might shift this.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    { "expr": "trade_info_age_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "drop rate (1/seconds)",
   "type": "timeseries",
   "description": "rate of received transactions - rate of published transactions",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(trades_received_total[$__rate_interval]) - rate(trades_published_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trade event delay (microseconds)",
   "type": "timeseries",
   "description": "trade event receive - publish delay",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    { "expr": "trade_event_delay_microseconds", "legendFormat": "__auto" }
   ]
  }
 ]
}