{
 "title": "services",
 "description": "Received & Published trade counts, data age, processing latencies.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "trade info rate (1/seconds)",
   "type": "timeseries",
   "description": "rate of received trade info from binance\nrate of published trade info to redis",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(trades_received_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(trades_published_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trade event delay (microseconds)",
   "type": "timeseries",
   "description": "trade event receive - publish delay",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    { "expr": "trade_event_delay_microseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "trade info error rate (1/seconds)",
   "type": "timeseries",
   "description": "rate of received transactions - rate of published transactions.\n\nthis indicates to either wrong json from binance, redis issues.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(trades_received_total[$__rate_interval]) - rate(trades_published_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trade info age (milliseconds)",
   "type": "timeseries",
   "description": "quantiles of the:\nsystem date - trade date\n(note: system date errors might shift this.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    { "expr": "trade_info_age_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BTCUSDT Price & SMAs",
   "type": "timeseries",
   "description": "Price & SMA",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    { "expr": "aggregate_info_price", "legendFormat": "__auto" },
    { "expr": "aggregate_info_sma50", "legendFormat": "__auto" },
    { "expr": "aggregate_info_sma200", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "aggregate info delay (milliseconds)",
   "type": "timeseries",
   "description": "system time of aggregate generation vs. timestamp on trade info. note: this can shift with system time errors.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "aggregate_info_age_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buy-Sell Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(aggregate_info_buy_count[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(aggregate_info_sell_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}