global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'fetcher'
    static_configs:
      - targets: ['fetcher:2112']

  - job_name: 'aggregator'
    static_configs:
      - targets: ['aggregator:2112']